services:
  backend:
    build: ./lib
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/host_tmp
    depends_on:
      - frontend

  frontend:
    build: ./vue/frontend
    ports:
      - "5173:5173"
